# Generated by Django 4.2 on 2024-01-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
