# Generated by Django 4.2 on 2024-01-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_client_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='signed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='uuid_document',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
